### ISSUE TITLE
Missing custom.http.d.ts

### ISSUE THREAD

**Issue by jneveux** [AngularShowcase/angular2-sample-app#1]
Hi,

I tried to build the application, and it looks like custom.http.d.ts is missing:

.../angular2-demo-app2/typings/tsd.d.ts(3,1): error TS6053: File '.../angular2-demo-app2/typings/custom.http.d.ts' not found.

Regards,

Jean

**Comment by ludohenin** [comment]
@jneveux thanks for pointing it, tsd.d.ts file is out-of-date actually. this is not required anymore.
Will update that one.
